(TeX-add-style-hook "triModalPersonReId"
 (lambda ()
    (LaTeX-add-bibliographies
     "references")
    (LaTeX-add-labels
     "sec:introduction"
     "sec:related-work"
     "sec:registration"
     "sec:feat-re-ident"
     "sec:features"
     "sec:re-identification"
     "sec:person-database"
     "sec:test-experiments"
     "sec:dataset"
     "fig:rgbSample"
     "fig:depthSample"
     "fig:thermalSample"
     "fig:datasetSamples"
     "sec:results"
     "sec:disc-future-work"
     "sec:conclusions"
     "fig:long"
     "fig:onecol")
    (TeX-add-symbols
     "cvprPaperID"
     "httilde")
    (TeX-run-style-hooks
     "hyperref"
     "colorlinks"
     "units"
     "fixme"
     "draft"
     "inline"
     "nomargin"
     "subcaption"
     "fontenc"
     "T1"
     "babel"
     "english"
     "inputenc"
     "utf8"
     "amssymb"
     "amsmath"
     "graphicx"
     "epsfig"
     "times"
     "cvpr"
     "latex2e"
     "art10"
     "article"
     "10pt"
     "twocolumn"
     "letterpaper")))

